# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-16 01:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
