# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-16 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crawlerDataBase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleName', models.CharField(max_length=100)),
                ('authorPos', models.CharField(max_length=20)),
                ('authorSex', models.CharField(max_length=20)),
                ('startTime', models.CharField(max_length=50)),
                ('people', models.CharField(max_length=50)),
                ('duringDay', models.CharField(max_length=50)),
                ('cost', models.CharField(max_length=20)),
                ('articleInfo', models.TextField()),
                ('keyWords', models.TextField()),
                ('href', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestAnswerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.CharField(max_length=100)),
                ('href', models.TextField(null=True)),
                ('pos', models.CharField(max_length=20)),
                ('qtitle', models.TextField()),
                ('qcontext', models.TextField()),
                ('qlabel', models.TextField()),
                ('qtime', models.TextField()),
                ('authorsex', models.CharField(max_length=20)),
                ('authorpos', models.CharField(max_length=20)),
                ('readtimes', models.TextField()),
                ('likenums', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestAnswerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.CharField(max_length=100)),
                ('href', models.TextField(null=True)),
            ],
        ),
    ]
